### ISSUE TITLE
[Device] ERROR: assertion failed

### ISSUE THREAD

**Issue by tweil** [sparkfun/Tomatoless_Boots#1]
I copied the code exactly and get these errors. Instead of using the Imp Shield, I used the Sparkfun Imp Breakout and Sparkfun Bi-directional Level Shifter, but I think I got everything hooked up correctly. Here  are the errors:

014-04-26 22:36:35 UTC-4: [Status] Device booting; 10.24% program storage used
2014-04-26 22:36:35 UTC-4: [Device] Device started, impee_id 237194eb6e4936ee and mac = 0c2a69003d10
2014-04-26 22:36:35 UTC-4: [Device] Bouncing the Arduino reset pin
2014-04-26 22:36:35 UTC-4: [Device] Bouncing complete
2014-04-26 22:36:36 UTC-4: [Device] ERROR: assertion failed
2014-04-26 22:36:36 UTC-4: [Device] ERROR: at execute:202
2014-04-26 22:36:36 UTC-4: [Device] ERROR: from check_duino:223
2014-04-26 22:36:36 UTC-4: [Device] ERROR: from unknown:273

**Comment by nseidle** [comment]
My guess is that the Imp is trying to control the three lines (RST, TX, RX) but something is preventing it. Perhaps it's the level shifter? Do you have a logic analyzer handy? Can you look at what is actually happening at the Arduino pins?

Also, be sure that you've got the correct Imp pins connected to the three RST/TX/RX pins.

Please let us know what you find out!

**Comment by tweil** [comment]
I will double check all the connections. One of the comments in the Device
code says,
"This code was modified slightly to work with the Electric Imp Shield
from SparkFun: https://www.sparkfun.com/products/11401
The reset control was inverted and status LEDs re-routed but everything
else was the same."

Is there anything I need to consider about the reset control line since I
am using an Imp Breakout along with the Sparkfun Bi--directional Logic
Shifter (Imp on LV side, Arduino on HV side), not the Imp Shield. I think I
have it all hooked up correctly including running the RST line through the
shifter in addition to the TX and RX lines.

**Comment by nseidle** [comment]
The original bootloader for imp to arduino was written by the amazing folks at Electric Imp. However, they wrote the code for their hardware (called [impeeduino](https://github.com/electricimp/reference/tree/master/hardware/impeeduino)). Near as I can figure they used a transistor to connect the Imp to the ATmega's RST line. This inverted the logic so on our tutorial, because the shield has built-in logic level conversion I removed this logic inversion from the code. Hence the (slightly confusing) comment.

I recommend removing the shifter for now. The RST pin should be pulled high with a 1k or more likely 10k to 5V. The Imp will try to control this to 3.3V but with a 10k limiter this shouldn't cause problems for either side.

**Comment by fiveghz** [comment]
I have also run into this problem using Sparkfun's red board and their imp shield.  It seems to happen when the power supply (a lipo battery in my case) is supplying less than 3.85v.  It seems to get stuck in this way forever, even if the voltage goes back up to acceptable levels.  The only way I've found to resolve it is to physically cut power to the arduino and then connect it back up.  Kinda defeats the purpose of being able to remotely reset the arduino...

**Comment by richrcr** [comment]
I just worked through the tutorial at https://learn.sparkfun.com/tutorials/wireless-arduino-programming-with-electric-imp and hit this same issue with the arduino not resetting.  As was suggested, pulling RST high with a 10k resistor between P1 and 3v3 on the imp shield solved the problem.

**Comment by fourstix** [comment]
I had the same issue with a Sparkfun red board, when using a 9v wall power source.  (The red board regulates Vin to 5v and the imp shield regulates 5v to 3.3v)  This seemed to drive the RST line too hard, and P1 wasn't driving RST low enough to cause the red board to reset reliably.  

So I added a 1uF capacitor in series with P1, and kept the pull up resistor on p1 for the case when Vin is too low.  This fixed the issue and allowed P1 to drive the line low, even when Vin was high.  If you use an electrolytic capacitor.  It's polarized and the positive end should go to RST and the negative end should go to P1, since P1 is bringing the line low.

**Comment by nseidle** [comment]
Thanks for letting us know your fix fourstix! Closing issue for now.

**Comment by scottosx** [comment]
I am having trouble getting code to run using this tutorial. I am using an Uno clone. (Sainsmart) Based on the above information I am led to believe that RST is not working. All else appears ok on the Imp side.

What then is the preferred solution as there are various recommendations above and could the tutorial be updated or pictures added?

**Comment by fourstix** [comment]
HI,

I don't own the tutorial, so I can't update it.  But would a quick schematic be helpful? Here's what I did to get the Imp shield to work for me:

![imp shield rst](https://cloud.githubusercontent.com/assets/5274281/8722522/84c1546a-2b93-11e5-8fef-407405225c9a.JPG)

I hope this helps.  

Good luck and best regards,
Tony

**Comment by scottosx** [comment]
The Imp shield seems to be somewhat picky with power supplies. I have gotten it to work with the single wire connection outlined in the tutorial on USB power and a brand new 9 volt battery. I see from the tutorial that the Imp pulls 400mA, so that is hungry.

The circuit above with the cap never did work for me but I see that you were using a 9v wall adapter. I may try that later. The resistor was also tried but removed as I first needed to see what was supposed to happen.

BTW, I got all kinds of weird status indicators on the Imp, finally ending up with flashing orange which I interpreted to mean 'No Wifi Settings' as indicated on this page: https://electricimp.com/docs/troubleshooting/blinkup/

However, it was actually 'red blinking' which indicated a power supply problem. Still it was 'amber' or orange flashing, not red (I have seen the red led during configuration and startup) So that is a discrepancy between the docs and my experience.

I will try with some LiPos later as well. Right now I just am happy to have something working and I want to play with remote programming more than power troubleshooting.

Thanks Tony for your help!
